=== gecata17/XML/auto.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT autoservice (automobile*)>
<!ELEMENT automobile (brand, model, horsepower, color, transmition, available_on_lising, count_of, buyer,
manifacturer, type, data)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT horsepower (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT transmition (#PCDATA)>
<!ELEMENT available_on_lising (#PCDATA)>
<!ELEMENT count_of (#PCDATA)>
<!ELEMENT buyer (name, personal_number, sum_of_purchase)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT personal_number (#PCDATA)>
<!ELEMENT sum_of_purchase (#PCDATA)>
<!ELEMENT manifacturer (name, company_info, headquarters, type_of_automobiles)>
<!ELEMENT type_of_automobiles (#PCDATA)>
<!ELEMENT headquarters (country, city, type)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT data (day, month, year)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT company_info (number_of_employees, boss, number_of_factories)>
<!ELEMENT number_of_employees (#PCDATA)>
<!ELEMENT boss (#PCDATA)>
<!ELEMENT number_of_factories (#PCDATA)>

<!ATTLIST available_on_lising isTrue CDATA #REQUIRED>
<!ATTLIST day value CDATA #REQUIRED>
<!ATTLIST month value CDATA #REQUIRED>
<!ATTLIST year value CDATA #REQUIRED>
<!ATTLIST count_of autos CDATA #REQUIRED>

=== gecata17/XML/valid_xml_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE autoservice SYSTEM "auto.dtd">

<autoservice>
    <automobile>
        <brand>Шкода</brand>
        <model>Октавия</model>
        <horsepower>150</horsepower>
        <color>Зелена</color>
        <transmition>Автоматична</transmition>
        <available_on_lising isTrue="ДА"></available_on_lising>
        <count_of autos="660"></count_of>
        <buyer>
            <name>Антон Ненков</name>
            <personal_number>86745231023</personal_number>
            <sum_of_purchase>5000.0</sum_of_purchase>
        </buyer>
        <manifacturer>
            <name>Шкода</name>
            <company_info>
                <number_of_employees>4000</number_of_employees>
                <boss>Велчо Валентинов</boss>
                <number_of_factories>200</number_of_factories>
            </company_info>
            <headquarters>
                <country>Чехия</country>
                <city>Прага</city>
                <type>Завод Централа</type>
            </headquarters>
            <type_of_automobiles>Седан лек автомобил</type_of_automobiles>
        </manifacturer>
        <type>Лек автомобил</type>
        <data>
            <day value="13"></day>
            <month value="5"></month>
            <year value="2009"></year>
        </data>
    </automobile>
</autoservice>

=== gecata17/XML/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE autoservice SYSTEM "auto.dtd">

<autoservice>
    <automobile>
        <brand>Сеат</brand>
        <model>Толедо</model>
        <horsepower>120</horsepower>
        <color>Бял</color>
        <transmition>Ръчна</transmition>
        <available_on_lising isTrue="НЕ"></available_on_lising>
        <count_of autos="34"></count_of>
        <buyer>
            <name>Киро Шейтанов</name>
            <personal_number>4567912345</personal_number>
            <sum_of_purchase>22000.0</sum_of_purchase>
        </buyer>
        <manifacturer>
            <name>Волксваген</name>
            <company_info>
                <number_of_employees>1200</number_of_employees>
                <boss>Мартин Мирчев</boss>
                <number_of_factories>30</number_of_factories>
            </company_info>
            <headquarters>
                <country>Дания</country>
                <city>Копенхаген</city>
                <type>Завод сграда</type>
            </headquarters>
            <type_of_automobiles>Комби лек автомобил</type_of_automobiles>
        </manifacturer>
        <type>Лек автомобил</type>
        <data>
            <day value="23"></day>
            <month value="10"></month>
            <year value="2020"></year>
        </data>
    </automobile>
</autoservice>

=== gecata17/XML/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE autoservice SYSTEM "auto.dtd">

<autoservice>
    <automobile>
        <brand>Мини Купър</brand>
        <model>EС</model>
        <horsepower>170</horsepower>
        <color>Сив Металик</color>
        <transmition>ПолуАвтоматична</transmition>
        <available_on_lising isTrue="ДА"></available_on_lising>
        <count_of autos="150"></count_of>
        <buyer>
            <name>Тошко Миленов</name>
            <personal_number>0312564511</personal_number>
            <sum_of_purchase>5400.0</sum_of_purchase>
        </buyer>
        <manifacturer>
            <name>БМВ</name>
            <company_info>
                <number_of_employees>5500</number_of_employees>
                <boss>Анатоли Тодоров</boss>
                <number_of_factories>48</number_of_factories>
            </company_info>
            <headquarters>
                <country>Холандия</country>
                <city>Амстердам</city>
                <type>Завод сграда</type>
            </headquarters>
            <type_of_automobiles>Сув</type_of_automobiles>
        </manifacturer>
        <type>Сув</type>
        <data>
            <day value="8"></day>
            <month value="4"></month>
            <year value="2009"></year>
        </data>
    </automobile>
</autoservice>

=== gecata17/XML/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE autoservice SYSTEM "auto.dtd">

<autoservice>
    <automobile>
        <brand>Ауди</brand>
        <model>100</model>
        <horsepower>75</horsepower>
        <color>Черен</color>
        <transmition>Ръчна</transmition>
        <available_on_lising isTrue="НЕ"></available_on_lising>
        <count_of autos="50"></count_of>
        <buyer>
            <name>Евгени Иванчев</name>
            <personal_number>4567341289</personal_number>
            <sum_of_purchase>1500.0</sum_of_purchase>
        </buyer>
        <manifacturer>
            <name>Волксваген</name>
            <company_info>
                <number_of_employees>1999</number_of_employees>
                <boss>Иван Киров</boss>
                <number_of_factories>120</number_of_factories>
            </company_info>
            <headquarters>
                <country>Германия</country>
                <city>Франкфурт</city>
                <type>Офис централа</type>
            </headquarters>
            <type_of_automobiles>Леки автомобили</type_of_automobiles>
        </manifacturer>
        <type>Лек автомобил</type>
        <data>
            <day value="5"></day>
            <month value="9"></month>
            <year value="2021"></year>
        </data>
    </automobile>
</autoservice>

=== gecata17/XML/valid_xml_1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<!DOCTYPE autoservice SYSTEM "auto.dtd">

<autoservice>
    <automobile>
        <brand>Мерцедес</brand>
        <model>124</model>
        <horsepower>90</horsepower>
        <color>Червен</color>
        <transmition>Автоматична</transmition>
        <available_on_lising isTrue="ДА"/>
        <count_of autos="30"></count_of>
        <buyer>
            <name>Иван Иванов</name>
            <personal_number>1234567890</personal_number>
            <sum_of_purchase>3000.0</sum_of_purchase>
        </buyer>
        <manifacturer>
            <name>Бенц</name>
            <company_info>
                <number_of_employees>2000</number_of_employees>
                <boss>Петър Петров</boss>
                <number_of_factories>100</number_of_factories>
            </company_info>
            <headquarters>
                <country>Германия</country>
                <city>Берлин</city>
                <type>Офис сграда</type>
            </headquarters>
            <type_of_automobiles>Леки автомобили</type_of_automobiles>
        </manifacturer>
        <type>Лек автомобил</type>
        <data>
            <day value="1"></day>
            <month value="1"></month>
            <year value="2004"></year>
        </data>
    </automobile>
</autoservice>
